language: node_js
node_js:
  - "8"
  - "9"
  - "10"
install:
  - npm install -g codecov
script:
  - yarn run test:coverage
  - codecov
git:
  depth: 3
cache:
  yarn: true
  directories:
  - node_modules
