language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "latest"
script:
  - yarn run test:verbose
git:
  depth: 3
cache:
  yarn: true
  directories:
  - node_modules
