language: node_js

node_js:
  - "8"
  - "9"
  - "10"

sudo: false

install:
  - yarn install
  - yarn install -g codecov

script:
  - yarn run test:coverage
  - codecov

cache:
  yarn: true
  directories:
  - node_modules
